### ISSUE TITLE
No cars are simulating 

### ISSUE THREAD

**Issue by radhareddy31** [codemerlin19/trafficRL#39]
Hello,

I have tried to run your project by following all the steps that are mentioned. I can see the SUMO-Gui file running, but no vehicles. At the end SUMO is terminating with some errors. 
Please help me in solving this problem.
![Screenshot from 2021-01-06 12-47-13](https://user-images.githubusercontent.com/58886102/103868295-9fceb880-50c0-11eb-9fb1-1b02484a17e2.png)

**Comment by rohit-gohri** [comment]
Hi @radhareddy31,
Will try to recreate this today.

**Comment by rohit-gohri** [comment]
From the error I can see that the problem is not with Sumo but that the code could not connect to MongoDB (27017 is the port used by MongoDB). We use MongoDB to store and update the current state of the system.

It could be that mongoDB was installed but the service was not started, could check it's status with:
`sudo service mongod status`

And restart it if not started:
`sudo service mongod restart`

**Comment by radhareddy31** [comment]
Thanks very much Rohit, yes thats the issue, resolved with the mongod restart.

**Comment by rohit-gohri** [comment]
Have tried to improve logs and docs in this https://github.com/arorashu/trafficRL/pull/40. Might help you out.
